### ISSUE TITLE
[BUG] - CHECK_MLST failure

### ISSUE THREAD

**Issue by johnsonj161** [CDCgov/phoenix#91] opened 2023-03-02 14:51 UTC
Hi. I am experiencing the error below when running a prelease of Phoenix v1.1.0 that you so graciously shared with me a month or so ago. This has occurred with two different Klebsiella isolates. I am not sure yet if those were the same ST type but I believe they were both novel.

```
Error executing process > 'PHOENIX:PHOENIX_EXTERNAL:CHECK_MLST (ISOLATE_1_230228)'

Caused by:
  Process `PHOENIX:PHOENIX_EXTERNAL:CHECK_MLST (ISOLATE_1_230228)` terminated with an error exit status (1)

Command executed:

  check_and_fix_MLST2.py --input ISOLATE_1_230228.tsv --taxonomy ISOLATE_1_230228.tax

  cat <<-END_VERSIONS > versions.yml
  "PHOENIX:PHOENIX_EXTERNAL:CHECK_MLST":
      check_mlst: 1.0
  END_VERSIONS

Command exit status:
  1

Command output:
  Parsing MLST file ...
  ('reg:0', 'source_file  Database  ST  locus_1 locus_2 locus_3 locus_4 locus_5 locus_6 locus_7 locus_8 lous_9  locus_10')
  ('reg:1', isolate_1_230228.filtered.scaffolds.fa\tklebsiella\t-\tgapA(3)\tinfB(6)\tmdh(2)\tpgi(1)\tphoE(7)\trpoB(131)\ttonB(41)')
  ('appending -', isolate_1_230228.filtered.scaffolds.fa\tklebsiella\t-\tgapA(3)\tinfB(6)\tmdh(2)\tpgi(1)\tphoE(7)\trpoB(131)\ttonB(41)')
  No srst2 input file provided
  ('Taxonomy:', 'Klebsiella', 'pneumoniae')
  [[isolate_1_230228.filtered.scaffolds.fa\tklebsiella\t-\tgapA(3)\tinfB(6)\tmdh(2)\tpgi(1)\tphoE(7)\trpoB(131)\ttonB(41)', 'mlst', isolate_1_230228.tsv']]
  ISOLATE_1_230228.filtered.scaffolds.fa    klebsiella      -       gapA(3) infB(6) mdh(2)  pgi(1)  phoE(7) rpoB(131)     tonB(41)
  ('Array of original itmes', isolate_1_230228.filtered.scaffolds.fa\nklebsiella\n-\ngapA(3)\ninfB(6)\nmdh(2)\npgi(1)\nphoE(7)\nrpoB(131)\ntonB(41)')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], [], 'standard', '2023-03-02'], ['3'], '3')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3'], 'standard', '2023-03-02'], ['6'], '6')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6'], 'standard', '2023-03-02'], ['2'], '2')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2'], 'standard', '2023-03-02'], ['1'], '1')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1'], 'standard', '2023-03-02'], ['7'], '7')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7'], 'standard', '2023-03-02'], ['131'], '131')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131'], 'standard', '2023-03-02'], ['41'], '41')
  ('Schemes found:', 1)
  [[isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02']]
  ('# of catted schemes found:', 1)
  (0, [isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02'])
  k
  []
  []
  [[isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02']]
  ('Trimmed catted: ', [[isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02']])
  ('-', ['3', '6', '2', '1', '7', '131', '41'])
  ('About to look into', [isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', 'Novel_profile', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02'])
  ('Looking to convert:', 'klebsiella')
  No match found
  ('Downloading profile file for:', 'No match found')
  No species matched your query.

Command error:
  Parsing MLST file ...
  ('reg:0', 'source_file  Database  ST  locus_1 locus_2 locus_3 locus_4 locus_5 locus_6 locus_7 locus_8 lous_9  locus_10')
  ('reg:1', isolate_1_230228.filtered.scaffolds.fa\tklebsiella\t-\tgapA(3)\tinfB(6)\tmdh(2)\tpgi(1)\tphoE(7)\trpoB(131)\ttonB(41)')
  ('appending -', isolate_1_230228.filtered.scaffolds.fa\tklebsiella\t-\tgapA(3)\tinfB(6)\tmdh(2)\tpgi(1)\tphoE(7)\trpoB(131)\ttonB(41)')
  No srst2 input file provided
  ('Taxonomy:', 'Klebsiella', 'pneumoniae')
  [[isolate_1_230228.filtered.scaffolds.fa\tklebsiella\t-\tgapA(3)\tinfB(6)\tmdh(2)\tpgi(1)\tphoE(7)\trpoB(131)\ttonB(41)', 'mlst', isolate_1_230228.tsv']]
  ISOLATE_1_230228.filtered.scaffolds.fa    klebsiella      -       gapA(3) infB(6) mdh(2)  pgi(1)  phoE(7) rpoB(131)     tonB(41)
  ('Array of original itmes', isolate_1_230228.filtered.scaffolds.fa\nklebsiella\n-\ngapA(3)\ninfB(6)\nmdh(2)\npgi(1)\nphoE(7)\nrpoB(131)\ntonB(41)')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], [], 'standard', '2023-03-02'], ['3'], '3')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3'], 'standard', '2023-03-02'], ['6'], '6')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6'], 'standard', '2023-03-02'], ['2'], '2')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2'], 'standard', '2023-03-02'], ['1'], '1')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1'], 'standard', '2023-03-02'], ['7'], '7')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7'], 'standard', '2023-03-02'], ['131'], '131')
  ([isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131'], 'standard', '2023-03-02'], ['41'], '41')
  ('Schemes found:', 1)
  [[isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02']]
  ('# of catted schemes found:', 1)
  (0, [isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02'])
  k
  []
  []
  [[isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02']]
  ('Trimmed catted: ', [[isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', '-', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02']])
  ('-', ['3', '6', '2', '1', '7', '131', '41'])
  ('About to look into', [isolate_1_230228.filtered.scaffolds.fa', 'klebsiella', 'Novel_profile', 7, ['gapA', 'infB', 'mdh', 'pgi', 'phoE', 'rpoB', 'tonB'], ['3', '6', '2', '1', '7', '131', '41'], 'standard', '2023-03-02'])
  ('Looking to convert:', 'klebsiella')
  No match found
  ('Downloading profile file for:', 'No match found')
  No species matched your query.
```

**Comment by nvlachos** [comment] 2023-03-08 14:31
Hi @johnsonj161. Thanks for identifying this bug. We have fixed it and will be releasing a small patch hopefully by the end of the week as we would also like to include another small fix.

**Comment by johnsonj161** [comment] 2023-03-08 15:30
Great, thank you @nvlachos! I will keep my eye out for patch.

**Comment by jvhagey** [comment] 2023-03-22 15:48
Address with [release v1.1.1](https://github.com/CDCgov/phoenix/releases/tag/v1.1.1). Closing, please reopen if the issue is unresolved.

**Closed by jvhagey** 2023-03-22 15:48 UTC
Labels: Bug
